name: Manual staging deploy

on:
  workflow_dispatch

permissions: read-all

jobs:
  Run:
    runs-on: [self-hosted, andy-server]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The repository has been cloned to the runner."
      - name: Start staging server
        run: |
          docker stop nycmesh-support-bot-test || true
          docker build -t nycmesh-support-bot-test .
          docker run -d --name nycmesh-support-bot-test -v "/home/ubuntu/.env:/app/.env" --rm nycmesh-support-bot-test
